spring:
  datasource:
    username: root
    password: 12345678
    # 加入時區報錯了，就增加一個時區的配置就OK了serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis
mybatis:
  type-aliases-package: com.wong.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml